#!/bin/bash
#SBATCH --nodes=2             
#SBATCH --ntasks=32         
#SBATCH --time=48:00:00             
#SBATCH --job-name=geccell4
#SBATCH --output=job_output_filename.%j.out  
##SBATCH --partition=standard

srun -n 64 ./*.ex inputs
